version: '3.2'
services:
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=moonsnacksfoods
      - MYSQL_USER=moonsnacksfoods
      - MYSQL_PASSWORD=moonsnacksfoods
      - MYSQL_DATABASE=db-moonsnacksfoods-01
    container_name: moonsnacksfoods-db-server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - '4444:80'
    environment:
      - PMA_HOST=moonsnacksfoods-db-server
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: moonsnacksfoods-phpmyadmin
networks:
  frontend:
  backend:
